// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $blog from "./routes/blog.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $positions from "./routes/positions.tsx";
import * as $positions_philosophy from "./routes/positions/philosophy.tsx";
import * as $positions_politics from "./routes/positions/politics.tsx";
import * as $projects from "./routes/projects.tsx";
import * as $Countdown from "./islands/Countdown.tsx";
import * as $DiscordLink from "./islands/DiscordLink.tsx";
import * as $MarkdownBlock from "./islands/MarkdownBlock.tsx";
import * as $SplashTextDisplay from "./islands/SplashTextDisplay.tsx";
import * as $splashTextsStore from "./islands/splashTextsStore.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/blog.tsx": $blog,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/positions.tsx": $positions,
    "./routes/positions/philosophy.tsx": $positions_philosophy,
    "./routes/positions/politics.tsx": $positions_politics,
    "./routes/projects.tsx": $projects,
  },
  islands: {
    "./islands/Countdown.tsx": $Countdown,
    "./islands/DiscordLink.tsx": $DiscordLink,
    "./islands/MarkdownBlock.tsx": $MarkdownBlock,
    "./islands/SplashTextDisplay.tsx": $SplashTextDisplay,
    "./islands/splashTextsStore.tsx": $splashTextsStore,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
