// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_name_ from "./routes/api/[name].tsx";
import * as $api_feed from "./routes/api/feed.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $positions from "./routes/positions.tsx";
import * as $positions_slug_ from "./routes/positions/[slug].tsx";
import * as $posts from "./routes/posts.tsx";
import * as $posts_slug_ from "./routes/posts/[slug].tsx";
import * as $projects from "./routes/projects.tsx";
import * as $DiscordLink from "./islands/DiscordLink.tsx";
import * as $MarkdownBlock from "./islands/MarkdownBlock.tsx";
import * as $SplashTextDisplay from "./islands/SplashTextDisplay.tsx";
import * as $splashTextsStore from "./islands/splashTextsStore.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/[name].tsx": $api_name_,
    "./routes/api/feed.tsx": $api_feed,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
    "./routes/positions.tsx": $positions,
    "./routes/positions/[slug].tsx": $positions_slug_,
    "./routes/posts.tsx": $posts,
    "./routes/posts/[slug].tsx": $posts_slug_,
    "./routes/projects.tsx": $projects,
  },
  islands: {
    "./islands/DiscordLink.tsx": $DiscordLink,
    "./islands/MarkdownBlock.tsx": $MarkdownBlock,
    "./islands/SplashTextDisplay.tsx": $SplashTextDisplay,
    "./islands/splashTextsStore.tsx": $splashTextsStore,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
