// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $blog from "./routes/blog.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $positions from "./routes/positions.tsx";
import * as $projects from "./routes/projects.tsx";
import * as $discordSummon from "./islands/discordSummon.tsx";
import * as $updateTime from "./islands/updateTime.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/blog.tsx": $blog,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/positions.tsx": $positions,
    "./routes/projects.tsx": $projects,
  },
  islands: {
    "./islands/discordSummon.tsx": $discordSummon,
    "./islands/updateTime.tsx": $updateTime,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
