name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy to Deno Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for authentication with Deno Deploy
      contents: read # Required to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: "deno task build"

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "personal-site-alyx-abcx"
          entrypoint: "_fresh/server.js"
          root: ""


